### ISSUE TITLE
Debian Bullseye Harrogate Errors

### ISSUE THREAD

**Issue by Zacharyprime** [kipr/harrogate#113]
I don't have much information as to why this is happening yet, but this is the next roadblock to getting harrogate working on a fresh image of RPiOS.
<details>
<summary>See Errors</summary>

```bash

pi@raspberrypi:~/harrogate $ npm install

npm ERR! code 1

npm ERR! path /home/pi/harrogate/node_modules/bufferutil

npm ERR! command failed

npm ERR! command sh -c node-gyp rebuild

npm ERR! make: Entering directory '/home/pi/harrogate/node_modules/bufferutil/build'

npm ERR!   CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

npm ERR! make: Leaving directory '/home/pi/harrogate/node_modules/bufferutil/build'

npm ERR! gyp info it worked if it ends with ok

npm ERR! gyp info using node-gyp@7.1.2

npm ERR! gyp info using node@12.22.5 | linux | arm

npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"

npm ERR! gyp info spawn /usr/bin/python3

npm ERR! gyp info spawn args [

npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',

npm ERR! gyp info spawn args   'binding.gyp',

npm ERR! gyp info spawn args   '-f',

npm ERR! gyp info spawn args   'make',

npm ERR! gyp info spawn args   '-I',

npm ERR! gyp info spawn args   '/home/pi/harrogate/node_modules/bufferutil/build/config.gypi',

npm ERR! gyp info spawn args   '-I',

npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',

npm ERR! gyp info spawn args   '-I',

npm ERR! gyp info spawn args   '/usr/include/nodejs/common.gypi',

npm ERR! gyp info spawn args   '-Dlibrary=shared_library',

npm ERR! gyp info spawn args   '-Dvisibility=default',

npm ERR! gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',

npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gy
p',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',

npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/pi/harrogate/node_modules/bufferutil',

npm ERR! gyp info spawn args   '-Dnode_engine=v8',

npm ERR! gyp info spawn args   '--depth=.',

npm ERR! gyp info spawn args   '--no-parallel',

npm ERR! gyp info spawn args   '--generator-output',

npm ERR! gyp info spawn args   'build',

npm ERR! gyp info spawn args   '-Goutput_dir=.'

npm ERR! gyp info spawn args ]

npm ERR! gyp info spawn make

npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]

npm ERR! ../src/bufferutil.cc:25:30: error: ‘v8::Handle’ has not been declared

npm ERR!    25 |   static void Initialize(v8::Handle<v8::Object> target)

npm ERR!       |                              ^~~~~~
npm ERR! ../src/bufferutil.cc:25:36: error: expected ‘,’ or ‘...’ before ‘<’ token

npm ERR!    25 |   static void Initialize(v8::Handle<v8::Object> target)

npm ERR!       |                                    ^

npm ERR! ../src/bufferutil.cc: In static member function ‘static void BufferUtil::Initialize(int)’:

npm ERR! ../src/bufferutil.cc:33:14: error: ‘target’ was not declared in this scope

npm ERR!    33 |     Nan::Set(target, Nan::New<String>("BufferUtil").ToLocalChecked(), t->GetFunction());

npm ERR!       |              ^~~~~~

npm ERR! ../src/bufferutil.cc:33:86: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’

npm ERR!    33 |     Nan::Set(target, Nan::New<String>("BufferUtil").ToLocalChecked(), t->GetFunction());

npm ERR!       |                                                                                      ^

npm ERR! In file included from ../src/bufferutil.cc:7:

npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:6126:46: note: candidate: ‘v8::MaybeLocal<v8::Function> 

v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’

npm ERR!  6126 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(

npm ERR!       |                                              ^~~~~~~~~~~

npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:6126:46: note:   candidate expects 1 argument, 0 provided

npm ERR! ../src/bufferutil.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE 

BufferUtil::Merge(Nan::NAN_METHOD_ARGS_TYPE)’:

npm ERR! ../src/bufferutil.cc:49:49: error: no matching function for call to ‘v8::Value::ToObject()’

npm ERR!    49 |     Local<Object> bufferObj = info[0]->ToObject();

npm ERR!       |                                                 ^

npm ERR! In file included from ../src/bufferutil.cc:7:

npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note: candidate: ‘v8::MaybeLocal<v8::Object> 
v8::Value::ToObject(v8::Local<v8::Context>) const’

npm ERR!  2672 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(

npm ERR!       |                                            ^~~~~~~~

npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided

npm ERR! In file included from /usr/include/nodejs/deps/v8/include/v8-internal.h:14,

npm ERR!                  from /usr/include/nodejs/deps/v8/include/v8.h:27,

npm ERR!                  from ../src/bufferutil.cc:7:

npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) 
const’

npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);

npm ERR!       |                               ^~~~~~~~

npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’

npm ERR!   328 |   declarator __attribute__((deprecated(message)))

npm ERR!       |   ^~~~~~~~~~

npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided

npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);

npm ERR!       |                               ^~~~~~~~

npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’

npm ERR!   328 |   declarator __attribute__((deprecated(message)))

npm ERR!       |   ^~~~~~~~~~

npm ERR! ../src/bufferutil.cc:56:39: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated: Use maybe version [-Wdeprecated-declarations]

npm ERR!    56 |       Local<Object> src = array->Get(i)->ToObject();

npm ERR!       |                                       ^

npm ERR! In file included from /usr/include/nodejs/deps/v8/include/v8-internal.h:14,
npm ERR!                  from /usr/include/nodejs/deps/v8/include/v8.h:27,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:3557:51: note: declared here
npm ERR!  3557 |   V8_DEPRECATED("Use maybe version", Local<Value> Get(uint32_t index));
npm ERR!       |                                                   ^~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! ../src/bufferutil.cc:56:51: error: no matching function for call to ‘v8::Value::ToObject()’
npm ERR!    56 |       Local<Object> src = array->Get(i)->ToObject();
npm ERR!       |                                                   ^
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
npm ERR!  2672 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
npm ERR!       |                                            ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided
npm ERR! In file included from /usr/include/nodejs/deps/v8/include/v8-internal.h:14,
npm ERR!                  from /usr/include/nodejs/deps/v8/include/v8.h:27,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);
npm ERR!       |                               ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided
npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);
npm ERR!       |                               ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! ../src/bufferutil.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BufferUtil::Unmask(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! ../src/bufferutil.cc:67:50: error: no matching function for call to ‘v8::Value::ToObject()’
npm ERR!    67 |     Local<Object> buffer_obj = info[0]->ToObject();
npm ERR!       |                                                  ^
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
npm ERR!  2672 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
npm ERR!       |                                            ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided
npm ERR! In file included from /usr/include/nodejs/deps/v8/include/v8-internal.h:14,
npm ERR!                  from /usr/include/nodejs/deps/v8/include/v8.h:27,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);
npm ERR!       |                               ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided
npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);
npm ERR!       |                               ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! ../src/bufferutil.cc:69:48: error: no matching function for call to ‘v8::Value::ToObject()’
npm ERR!    69 |     Local<Object> mask_obj = info[1]->ToObject();
npm ERR!       |                                                ^
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
npm ERR!  2672 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
npm ERR!       |                                            ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided
npm ERR! In file included from /usr/include/nodejs/deps/v8/include/v8-internal.h:14,
npm ERR!                  from /usr/include/nodejs/deps/v8/include/v8.h:27,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);
npm ERR!       |                               ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided
npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);
npm ERR!       |                               ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! ../src/bufferutil.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BufferUtil::Mask(Nan::NAN_METHOD_ARGS_TYPE)’:
npm ERR! ../src/bufferutil.cc:88:50: error: no matching function for call to ‘v8::Value::ToObject()’
npm ERR!    88 |     Local<Object> buffer_obj = info[0]->ToObject();
npm ERR!       |                                                  ^
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
npm ERR!  2672 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
npm ERR!       |                                            ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided
npm ERR! In file included from /usr/include/nodejs/deps/v8/include/v8-internal.h:14,
npm ERR!                  from /usr/include/nodejs/deps/v8/include/v8.h:27,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);
npm ERR!       |                               ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided
npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);
npm ERR!       |                               ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! ../src/bufferutil.cc:89:48: error: no matching function for call to ‘v8::Value::ToObject()’
npm ERR!    89 |     Local<Object> mask_obj = info[1]->ToObject();
npm ERR!       |                                                ^
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
npm ERR!  2672 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
npm ERR!       |                                            ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided
npm ERR! In file included from /usr/include/nodejs/deps/v8/include/v8-internal.h:14,
npm ERR!                  from /usr/include/nodejs/deps/v8/include/v8.h:27,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);
npm ERR!       |                               ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided
npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);
npm ERR!       |                               ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! ../src/bufferutil.cc:91:50: error: no matching function for call to ‘v8::Value::ToObject()’
npm ERR!    91 |     Local<Object> output_obj = info[2]->ToObject();
npm ERR!       |                                                  ^
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note: candidate: ‘v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const’
npm ERR!  2672 |   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
npm ERR!       |                                            ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2672:44: note:   candidate expects 1 argument, 0 provided
npm ERR! In file included from /usr/include/nodejs/deps/v8/include/v8-internal.h:14,
npm ERR!                  from /usr/include/nodejs/deps/v8/include/v8.h:27,
npm ERR!                  from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note: candidate: ‘v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const’
npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);
npm ERR!       |                               ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2686:31: note:   candidate expects 1 argument, 0 provided
npm ERR!  2686 |                 Local<Object> ToObject(Isolate* isolate) const);
npm ERR!       |                               ^~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
npm ERR!   328 |   declarator __attribute__((deprecated(message)))
npm ERR!       |   ^~~~~~~~~~
npm ERR! ../src/bufferutil.cc:92:51: error: no matching function for call to ‘v8::Value::Int32Value()’
npm ERR!    92 |     unsigned int dataOffset = info[3]->Int32Value();
npm ERR!       |                                                   ^
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2709:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
npm ERR!  2709 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
npm ERR!       |                                        ^~~~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2709:40: note:   candidate expects 1 argument, 0 provided
npm ERR! ../src/bufferutil.cc:93:47: error: no matching function for call to ‘v8::Value::Int32Value()’
npm ERR!    93 |     unsigned int length = info[4]->Int32Value();
npm ERR!       |                                               ^
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2709:40: note: candidate: ‘v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const’
npm ERR!  2709 |   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
npm ERR!       |                                        ^~~~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:2709:40: note:   candidate expects 1 argument, 0 provided
npm ERR! ../src/bufferutil.cc: At global scope:
npm ERR! ../src/bufferutil.cc:114:6: error: variable or field ‘init’ declared void
npm ERR!   114 | void init (Handle<Object> target)
npm ERR!       |      ^~~~
npm ERR! ../src/bufferutil.cc:114:12: error: ‘Handle’ was not declared in this scope
npm ERR!   114 | void init (Handle<Object> target)
npm ERR!       |            ^~~~~~
npm ERR! ../src/bufferutil.cc:114:25: error: expected primary-expression before ‘>’ token
npm ERR!   114 | void init (Handle<Object> target)
npm ERR!       |                         ^
npm ERR! ../src/bufferutil.cc:114:27: error: ‘target’ was not declared in this scope
npm ERR!   114 | void init (Handle<Object> target)
npm ERR!       |                           ^~~~~~
npm ERR! In file included from ../src/bufferutil.cc:8:
npm ERR! ../src/bufferutil.cc:120:25: error: ‘init’ was not declared in this scope; did you mean ‘int’?
npm ERR!   120 | NODE_MODULE(bufferutil, init)
npm ERR!       |                         ^~~~
npm ERR! /usr/include/nodejs/src/node.h:736:36: note: in definition of macro ‘NODE_MODULE_X’
npm ERR!   736 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |                                    ^~~~~~~
npm ERR! ../src/bufferutil.cc:120:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR!   120 | NODE_MODULE(bufferutil, init)
npm ERR!       | ^~~~~~~~~~~
npm ERR! In file included from ../src/bufferutil.cc:7:
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
npm ERR! /usr/include/nodejs/src/node_object_wrap.h:85:78:   required from here
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:10226:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
npm ERR! 10226 |                reinterpret_cast<Callback>(callback), type);
npm ERR!       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
npm ERR! ../../nan/nan_object_wrap.h:65:61:   required from here
npm ERR! /usr/include/nodejs/deps/v8/include/v8.h:10226:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
npm ERR! make: *** [bufferutil.target.mk:108: Release/obj.target/bufferutil/src/bufferutil.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
npm ERR! gyp ERR! System Linux 5.15.36-v7+
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/share/nodejs/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /home/pi/harrogate/node_modules/bufferutil
npm ERR! gyp ERR! node -v v12.22.5
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-05-17T15_42_20_736Z-debug.log

```

</details>

**Comment by Zacharyprime** [comment]
I was running commands with && so I didn't realize this until now, but these errors occur even when installing individual packages like:
```
npm install browserfy
npm install gulp
etc.
```

I believe I've seen a similar issue before. I recall there being an issue with installing npm through Aptitude, so my next step is to try to install npm through whatever the official documentation suggests.

The behavior above makes me think this is a problem with npm itself and not harrogate

**Comment by Zacharyprime** [comment]
Attempt 1:
```
#Install node
sudo curl https://deb.nodesource.com/setup_18.x | sudo bash

```
(continuously editing this comment)

**Comment by Zacharyprime** [comment]
I did not change anything from my last comment, but now it is working.
Maybe it just needed a reboot

I'm going to leave this open until I do another pass through of the build a wombat recipe so I can be certain that this is how we want to do it.

**Comment by Zacharyprime** [comment]
I've been past that last error. These are the versions that I have npm install working on:
```
npm: v8.9.0
nodejs: v18.2.0

Gulp:
CLI version: v2.3.0
Local version: v4.0.2
```

Now I am getting the following error (after having to fix the package.json to update bufferutil and utf-8-validate to latest):
<details>
<summary>See Error</summary>

```
pi@raspberrypi:~/dev/harrogate $ gulp
ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/home/pi/dev/harrogate/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/pi/dev/harrogate/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/pi/dev/harrogate/node_modules/gulp-nodemon/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)


```

</details>

**Comment by Zacharyprime** [comment]
https://www.npmjs.com/package/graceful-fs
